spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:C:\Database-iWallet
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate-hbm2ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true

